version: '3.7'

networks:
  dashboard-net:
    driver: bridge

#volumes:

services:
  # Manutal build / start of the python-django-app
  # docker build -t python-django-app .
  # docker run -it -p 8000:8000 python-django-app
  python-django-app:
    build: ./app
    #command: python3 /code/manage.py runserver localhost:8000
    ports:
      - 8000:8000
    networks:
      - dashboard-net
    volumes:
      - ./app:/code
